# Generated by Django 3.1.2 on 2021-01-13 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210113_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 13, 9, 15, 46, 283167, tzinfo=utc)),
        ),
    ]
