# Generated by Django 3.1.2 on 2021-01-13 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210113_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='date',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='pub_date',
            field=models.DateTimeField(default=timezone.now(), verbose_name=datetime.datetime(2021, 1, 13, 9, 21, 39, 358019, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
