# Generated by Django 3.1.2 on 2021-01-13 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210113_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 13, 10, 37, 10, 636670, tzinfo=utc)),
        ),
    ]
