# Generated by Django 3.1.2 on 2021-01-22 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210115_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 1, 22, 15, 32, 11, 605582, tzinfo=utc)),
        ),
    ]
