# Generated by Django 3.1.2 on 2021-01-15 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
